---
output:
  bookdown::html_document2: 
    nature: 
      beforeInit: "https://platform.twitter.com/widgets.js"
    toc: true
    toc_float: true
    toc_depth: 4
title: Political science blog
---
<br />
<br />

# Prophetic punditry and sensible suggestions: political science's response to Corbyn's electoral failure {-}
<br />

__*Every political scientist and pundit has an opinion on what is next for Labour and what should be next for Labour, but they are all as politically motivated as one another.*__

The result of the 2019 UK general election came as a shock to pundits and political scientists alike, whether they admit it or not. Despite vote shares that were not far off those in the polls for a few weeks prior, the difference in number of seats won by the two major parties was of a scale few had anticipated. Every British political scientist and pundit appears to have taken to Twitter, determined to establish what Labour *should* do in response to this, if not what it *will* do.     

## Prophetic punditry {-}

Nonetheless, as 'scientists', it is often expected of us that we have an answer to questions like the latter. We have data, we have theory, what good are we if we cannot use them to predict the future? This, I would argue, is a troubling way to think about social science and is almost certainly tied up with why experts are supposedly no longer trusted. A particular problem for political science is that people's main exposure to it is through opinion polls, which -- despite [insistence to the contrary](https://www.washingtonpost.com/news/monkey-cage/wp/2013/12/10/a-poll-is-a-snapshot-not-a-forecast/) -- are at least *understood* as being predictions. Thereby 'incorrect' polls become an indictment of our discipline.        

Yet, although we might believe in avoiding this association of political science as a predictor of electoral futures, we occasionally can't help but dabble in prophecy. It seems reasonable to expect our predictions to be uncommonly sound and that people should attach some weight to them. We have data, we have theory. But of course, often we don't. What is (read: 'are') the data, let alone theory, on which to base any sort of prediction of who, for example, the next leader of the Labour Party will be? By now, perhaps we have betting odds. We don't have a poll of the members who choose the leader, or anything approximating such an 'objective' measure. We don't have data, we have *priors*.     

We also don't really have theory. What we have theory about, instead, is how people nonetheless making these predictions come about arriving at their conclusions. [Andrew Little argues](https://onlinelibrary.wiley.com/doi/full/10.1111/ajps.12435), essentially, that beliefs about politics are updated in response to new information all the time, starting with a 'prior' and changing in accordance with new 'likelihoods'. In terms of the Labour leadership, a given person might have a belief, say, about how likely it is that the leader will be from the left of the party. With time, once a contest is underway, membership polling and other information might start to reshape this perceived probability, but absent any such information, the person only has their prior. This prior will likely be very 'wide' or uncertain, meaning essentially that the probability of a leader coming from the left could be anything from very unlikely to very likely. That is, fairly even probability is assigned to these 'probabilities' of a left-wing candidate taking over -- because how on Earth could we possibly know?          

Little's main point, however, is that in drawing a 'conclusion' about such a belief, we are prone to substantial bias or 'distortion' when the belief pertains to something over which we have a clear preference. Most people involved in British politics have a meaningful preference about what sort of politician they'd like to see as the new Labour leader.[^1] When they then tell you what they predict will happen, this preference -- we theorise -- will distort how they draw from the probable outcomes.     

This much is 'just' theory, but take a post-election experience of mine as anecdotal evidence. Two anonymous academics, one more sympathetic to 'Corbynism' and the other broadly disillusioned with the Labour party in recent years, standing before a group of mostly disheartened activists, are asked 'what next?'. The Corbyn sympathiser arrives at the conclusion that the party would likely elect a new leader from the left of its ranks. Her colleague responds that, no, someone from the centre is more likely. What is the difference here? Both are British politics experts, both have a deep understanding of the Labour Party, there is no information disparity. The difference is in their *preferences*. I like to call opinions such as these 'blank slate' predictions. Our considerable capacity for [wishful thinking](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1559-1816.1991.tb00514.x) and little else, even as 'objective' scientists, determines what we predict.     

## Sensible suggestions {-}

If we are capable of such distortion when making supposedly objective *predictions*, it seems likely that we will be even worse at making *suggestions*. These have, indeed, been far more common in the days since the election. While we are aware of the uncertainty of our priors about what will happen, we seem all too certain about what should happen, and happy to say what that is.     

This suggestion-making has been characterised by a tendency to urge Labour back to 'sensible' territory. Corbyn failed, twice, and this time miserably. The country has rejected his politics. You can't win an election from the left. Stop blaming Brexit. Listen to the #PeopleOnTheDoorstep. This is tiresome not because I disagree, but because it is founded on false pretences about its motivations. It is convenient for these suggestion-makers that the politics to which they are advocating a return is one which aligns with the perceived character of their profession; 'sensible' centrism appears the logical suggestion for an academic -- particularly, a quantitative social scientist -- to make. What works. What wins elections. What comes as close as possible to Tory without being Tory. Blue Labour. Probably one of the Milibands, but not the dad and not the one who already lost that one time. Moderation. How could someone whose career is about truth, knowledge, arriving at informed conclusions, possibly advocate anything else?      

It is precisely because their suggestions 'make sense' that these people are able to mask ideological preferences behind some notion of objectivity, which is of course nearly always a mirage. I want to argue that, instead, these suggestions are no less ideological than the statements made by those on the left of the party, imploring it to continue on its current trajectory. We miss this because we mistake perceived ideological extremity for ideology *per se*, or for fanaticism, or radicalism in its negative sense. Those who advocate a centrist politics are somehow beyond ideology because of their supposed moderation, the 'consensual' support for their position.    

Of course, we should also allow room for the possibility that many of these commentators are honest in their motivations. They want a Labour government -- or anything but a Conservative one -- and in their experience it was Tony Blair who made this a reality. If a more 'moderate' politics is how Labour get into power then this is what they should pursue. This just simply is not the whole picture. We know too much about political psychology to buy that it is. Even if it were the whole picture, ideological pragmatism is not some normatively laudable virtue. Political scientists *know this*, so it is just not tenable to imagine that they all but unanimously ignore it in order to keep the Tories out.     

The most troubling part of this is the tendency to accuse the 'other side' -- here, the (particularly, young) left of the Labour Party -- of somehow blindly ignoring the obvious and doing exactly what pundits are claiming they themselves are *not* doing. [Tom O'Grady](https://twitter.com/DrTomD_OG) takes issue with this in a recent Twitter thread, including the following tweets: 



<blockquote class="twitter-tweet"><p lang="en" dir="ltr">So when people of my age hear supposedly sensible centrists saying that they are naive and stupid for supporting a party, to their eyes, simply wants to end climate change, solve the housing crisis and improve public services, they are baffled. They think you&#39;re mad.</p>&mdash; Tom O&#39;Grady (DrTomD_OG) <a href="https://twitter.com/DrTomD_OG/status/1205450350276296704?ref_src=twsrc%5Etfw">December 13, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Why? Because the media constantly tells them that they are naive idiots for supporting a party that wants to address the issues they care about. It frankly looks like a conspiracy to them, and saying that Corbynism needs to die is going to make that much, much worse</p>&mdash; Tom O&#39;Grady (DrTomD_OG) <a href="https://twitter.com/DrTomD_OG/status/1205450354395111425?ref_src=twsrc%5Etfw">December 13, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I&#39;d like to urge fellow political scientists not to make the mistake of writing off the current Labour party intellectually. There is no way that the membership will elect a new leader that doesn&#39;t promise to continue Corbynism. Let&#39;s not call those people naive fools</p>&mdash; Tom O&#39;Grady (DrTomD_OG) <a href="https://twitter.com/DrTomD_OG/status/1205450357029167106?ref_src=twsrc%5Etfw">December 13, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


The pursual of so-called 'Corbynism' -- [written off](https://link.springer.com/article/10.1057%2Fs41293-019-00115-6) since its inception by political science and punditry -- is seen as a purely ideological naivety which will get the party nowhere electorally and therefore should be abandoned. But, of course, as [Professor Will Jennings](https://twitter.com/drjennings/status/1206362405804158976) puts it, 'political parties are coalitions of diverse interests, identities and opinions'. To expect proponents of one such opinion to completely change their minds just because it came to the fore and did not lead to electoral success is farfetched. To do this while belittling these people, handing out I-told-you-so's about the superiority of the good old New Labour days, under the guise of electoral pragmatism, is farcical. The Labour Party is known to be a [broad church](https://theconversation.com/labour-conference-a-major-stress-test-for-the-broad-church-103540), and it will continue to be so, and its diverse 'interests, identities and opinions' will continue to be defended by those holding them. Rightly so. Politics *is* diversity.     

The point of political engagement is surely to pursue a vision of what one thinks the world should be. That many political scientists do not agree with the left of the Labour Party on what that world looks like is not the problem. The problem is the idea that this is not an ideological disagreement, but a battle between something sensible and something naive, that it's purely about 'what works'. The idea that we can and should hide behind objectivity is flawed, because political objectivity among highly politically engaged actors is an illusion. So let's stop pretending our suggestions and predictions aren't biased, while everyone else's are, or stop making them at all.      


# Other posts {-}

<a href="2019-08-22-dag-kam.html">DAGging the problem with conditioning on a pre-treatment moderator</a>  








[^1]: I am simplifying here. What these people likely have are more general ideological and partisan 'core beliefs' which the Labour leadership is associated with as an 'auxiliary belief'. 









